version: "3.7"
services:
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: perntodo
  web:
    image: server
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - webnet
    environment:
      DB_HOST: db
networks:
  webnet:
