version: "3.7"
services:
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: mohanad
      POSTGRES_DB: perntodo
  web:
    image: server
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - webnet
    environment:
      DB_HOST: db
networks:
  webnet:
